services:

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "8200:3000"
    env_file: .env      
    environment:
      TRACKER_SCRIPT_NAME: getinfo
      API_COLLECT_ENDPOINT: all
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    env_file: .env    
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    
